# This is an example wordlist to use with the check_difficult_words test.
# It is in the form of a hash where the key is the phrase to look for and the value
# is the recommended alternative word/phrase.
#
# In swedish: Denna ordlista är baserad på "Svarta listan- Ord och fraser 
# som kan ersättas i författningsspråk". Ordlistan ges ut av rättschefen
# i Statsrådsberedningen och har utarbetats av språkexperterna på 
# Justitiedepartementets granskningsenhet.
#
# För mer information se: http://www.regeringen.se/sb/d/243/a/19775

SVARTA_LISTAN = {
	"anhängiggöra" => "Skriv hellre 'väcka/inleda'.",
	"anbringa" => "Skriv hellre 'sätta upp/sätta på/placera/fästa (på något)'.",
	"anmana" => "Skriv hellre 'uppmana'.",
	"anmaning" => "Skriv hellre 'uppmaning'.",
	"anmoda" => "Skriv hellre 'uppmana'.",
	"anmodan" => "Skriv hellre 'uppmaning'.",
	"anmodas" => "Skriv hellre 'uppmanas'.",
	"avbida" => "Skriv hellre 'invänta/vänta (på)/avvakta'.",
	"avbidan" => "Skriv hellre 'väntan'.",
	"avge" => "Skriv hellre 'ge (bud), lämna (anbud, rapport m.m.)'.",
	"avnämare" => "Skriv hellre 'användare/mottagare/konsument/kund'.",
	"avskrift" => "Skriv hellre 'kopia'.",
	"avsända" => "Skriv hellre 'sända/skicka (i väg)'.",
	"belägen" => "Skriv hellre 'ligger (i)'.",
	"bereda" => "Skriv hellre 'ge/låta'.",
	"beskaffenhet" => "Skriv hellre 'art/slag/sort'.",
	"utan dröjsmål" => "Skriv hellre 'genast/omedelbart/snarast/möjligt'.",
	"därvid" => "Skriv hellre 'då/i det sammanhanget'.",
	"efterkomma" => "Skriv hellre 'lyda/följa'.",
	"efterlevas" => "Skriv hellre 'följas'.",
	"eljest" => "Skriv hellre 'annars/annat/på annat sätt/av andra skäl/i övrigt/av någon annan anledning'.",
	"envar" => "Skriv hellre 'var och en'.",
	"ettvart" => "Skriv hellre 'vart och ett'.",
	"erfara" => "Skriv hellre 'få veta'.",
	"erfordra" => "Skriv hellre 'behövs/krävs/är nödvändigt'.",
	"erfordras" => "Skriv hellre 'behövs/krävs/är nödvändigt'.",
	"erforderliga" => "Skriv hellre 'behövs/krävs/är nödvändigt'.",
	"erforderlig" => "Skriv hellre 'nödvändig/tillräcklig'.",
	"erhålla" => "Skriv hellre 'få'.",
	"erinran" => "Skriv hellre 'upplysning (om)'.",
	"erinra" => "Skriv hellre 'invända'.",
	"erlägga" => "Skriv hellre 'betala'.",
	"foga" => "Skriv hellre 'lämna (in) (tillsammans med)'.",
	"föranleda" => "Skriv hellre 'det finns'.",
	"föranleder" => "Skriv hellre 'det finns'.",
	"föranstalta" => "Skriv hellre 'ordna så/ordna med/sörja för/se till'.",
	"förebringa" => "Skriv hellre 'lägga fram/lämna'.",
	"föreligga" => "Skriv hellre 'finnas'.",
	"föreligger" => "Skriv hellre 'det finns'.",
	"företa" => "Skriv hellre 'göra'.",
	"förete" => "Skriv hellre 'visa (upp)'.",
	"förfaller till betalning" => "Skriv hellre '(senast) skall betalas'.",
	"förfara" => "Skriv hellre '(skall) göra'.",
	"förflutit" => "Skriv hellre 'det har gått'.",
	"förordna" => "Skriv hellre 'besluta/bestämma/utse'.",
	"försorg" => "Skriv hellre 'se till att'.",
	"förutskicka" => "Skriv hellre 'meddela på förhand/i förväg'.",
	"handha" => "Skriv hellre 'ha hand om/sköta'.",
	"hemställa" => "Skriv hellre 'begära/föreslå'.",
	"hörsamma" => "Skriv hellre 'följa/lyda/rätta sig efter'.",
	"ikläda" => "Skriv hellre 'ta på'.",
	"inhämta" => "Skriv hellre 'skaffa'.",
	"inkomma med" => "Skriv hellre 'lämna in/skicka in/sända över'.",
	"jämförlig" => "Skriv hellre 'liknande'.",
	"jämka" => "Skriv hellre 'sänka/minska/sätta ned/ner/(för)ändra'.",
	"lagfaren" => "Skriv hellre 'vara jurist/som avlagt jur.kand. examen/med jur.kand.-examen'.",
	"lagrum" => "Skriv hellre 'bestämmelse/paragraf'.",
	"lända till förfång" => "Skriv hellre 'skada/vara till skada'.",
	"medge anstånd" => "Skriv hellre 'bevilja anstånd'.",
	"nyttja" => "Skriv hellre 'använda'.",
	"nöjaktig" => "Skriv hellre 'godtagbar/som får godtas'.",
	"olägenhet" => "Skriv hellre 'besvär/problem'.",
	"oundgänglig" => "Skriv hellre 'nödvändig/absolut'.",
	"påkalla" => "Skriv hellre 'begära/kräva'.",
	"utom riket" => "Skriv hellre 'utomlands/utanför Sverige'.",
	"rådrum" => "Skriv hellre 'tid (på sig)'.",
	"stadfästa" => "Skriv hellre 'godkänna, fastställa, bekräfta'.",
	"stadgas" => "Skriv hellre 'föreskrivs'.",
	"såvitt avser" => "Skriv hellre 'när det gäller/i fråga om'.",
	"tillkommer" => "Skriv hellre 'har'.",
	"tillskapa" => "Skriv hellre 'bilda, inrätta, skapa'.",
	"tillställa" => "Skriv hellre 'lämna/ge/sända/skicka till'.",
	"tillställas" => "Skriv hellre 'lämna/ge/sända/skicka till'.",
	"underlåta" => "Skriv hellre 'låta bli/inte'.",
	"uppbära" => "Skriv hellre 'få/ha'.",
	"ersättning utgår" => "Skriv hellre 'ersättningen betalas (ut)/lämnas'.",
	"utröna" => "Skriv hellre 'ta reda på/klarlägga'.",
	"vederlag" => "Skriv hellre 'ersättning/motprestation'.",
	"ådöma" => "Skriv hellre 'döma till/döma ut'.",
	"ådömas" => "Skriv hellre 'dömas till/dömas ut'.",
	"åligger" => "Skriv hellre 'är skyldig (att)/skall/har'.",
	"åligganden" => "Skriv hellre 'skyldigheter'.",
	"åsätta" => "Skriv hellre 'fastställa'.",
	"åsatts" => "Skriv hellre 'fastställts'.",
	"åtnjuta" => "Skriv hellre 'få/ha/beviljas'.",
	"åtnjuter" => "Skriv hellre 'har'.",
	"åtnjutit" => "Skriv hellre 'fått'.",
}
